"""auto-vote

Revision ID: 962796fa13ca
Revises: 0302749e6b39
Create Date: 2023-05-24 14:44:16.785131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962796fa13ca'
down_revision = '0302749e6b39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
